graphqlapi:
  port: 8081
  enableintrospection: true

tokenvalidator:
  validatortype: "firebase"
  jwtjwksurl: ""

mcpapi:
  port: 8082

firebase:
  serviceaccountjson: ""

db:
  url: "postgres://deploy:deploy@localhost:5432/deploymcp?sslmode=disable"
  maxconns: 10
  minconns: 2
  maxconnlifetime: "30m"
  maxconnidletime: "5m"

github:
  clientid: ""
  clientsecret: ""
  callbackurl: "http://localhost:8081/auth/github/callback"
  scopes:
    - read:user
    - user:email

githubapp:
  appid: 2764764
  privatekey: ""
  clientid: ""
  clientsecret: ""
  webhooksecret: ""

auth:
  jwtsecret: ""
  jwtexpiry: "24h"
  apikeyencryptionkey: ""
  frontendurl: "http://localhost:5001"

openrouter:
  apikey: ""

openai:
  apikey: ""

temporal:
  address: "localhost:7233"
  namespace: "default"
  cloudapikey: ""

nats:
  url: "nats://localhost:4222"
  token: ""

cloudflare:
  apitoken: ""
  zoneid: ""
  basedomain: "ml.ink"
  cnametarget: "cname.ml.ink"

turso:
  apikey: ""
  orgslug: ""

gitea:
  baseurl: "https://git.ml.ink"
  admintoken: ""
  userprefix: "u"
  webhooksecret: ""
  webhookurl: "http://localhost:8081/webhooks/internal-git"

mcpoauth:
  issuer: "http://localhost:8081"
  frontendurl: "http://localhost:5001"

loki:
  queryurl: "https://loki.ml.ink/loki/api/v1/query_range"
  username: ""
  password: ""

prometheus:
  queryurl: "https://prometheus.ml.ink/api/v1/query_range"
  username: ""
  password: ""

k8sworker:
  buildkithost: "tcp://buildkitd.dp-system:1234"
  registryhost: "http://registry.dp-system.svc.cluster.local:5000"
  registryaddress: "registry.internal:5000"
  lokipushurl: "http://loki.dp-system.svc.cluster.local:3100/loki/api/v1/push"
  lokiqueryurl: "http://loki.dp-system.svc.cluster.local:3100/loki/api/v1/query_range"

cluster:
  region: "eu-central-1"
