---
ssh_port: 22
metadata_ip: 169.254.169.254
smtp_ports:
  - "25"
  - "465"
  - "587"

registry_allowed_cidrs:
  - "{{ vswitch_network_cidr }}"

metrics_allowed_cidrs:
  - "{{ vswitch_network_cidr }}"

traefik_public_ports:
  - "80"
  - "443"

traefik_private_probe_ports:
  - "8080"
  - "19100"

# If non-empty, restrict Traefik public ports to these source CIDRs only.
# If empty, allow from anywhere (current default behavior).
traefik_public_allowed_sources: []
