apiVersion: v1
kind: ServiceAccount
metadata:
  name: ci-deployer
  namespace: dp-system
---
apiVersion: v1
kind: Secret
metadata:
  name: ci-deployer-token
  namespace: dp-system
  annotations:
    kubernetes.io/service-account.name: ci-deployer
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ci-deployer
  namespace: dp-system
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "patch"]
    resourceNames: ["deployer-worker", "deployer-server"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ci-deployer
  namespace: dp-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ci-deployer
subjects:
  - kind: ServiceAccount
    name: ci-deployer
    namespace: dp-system
