apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: prometheus-auth
  namespace: dp-system
spec:
  basicAuth:
    secret: prometheus-auth-secret
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prometheus
  namespace: dp-system
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: dp-system-prometheus-auth@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
    - host: prometheus.ml.ink
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: prometheus-kube-prometheus-prometheus
                port:
                  number: 9090
