---
hetzner_lb_name: load-balancer-central-1
hetzner_lb_type: lb11
hetzner_lb_location: fsn1
hetzner_lb_network: "{{ hetzner_cloud_network_id }}"
hetzner_lb_services:
  - protocol: tcp
    listen_port: 80
    destination_port: 80
  - protocol: tcp
    listen_port: 443
    destination_port: 443
